"""job profile

Revision ID: 1446f0c589c8
Revises: cb4c30b3a7b8
Create Date: 2026-09-04 13:52:19.315652
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '1446f0c589c8'
down_revision: Union[str, None] = 'cb4c30b3a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clip_jobs', schema=None) as batch_op:
        # server_default, so jobs created before profiles existed keep working:
        # without it the rebuild SQLite does for an ALTER has no value to put
        # in the new column for existing rows.
        batch_op.add_column(sa.Column('profile', sqlmodel.sql.sqltypes.AutoString(length=16),
                                      nullable=False, server_default='talking'))
        batch_op.create_index(batch_op.f('ix_clip_jobs_profile'), ['profile'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clip_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clip_jobs_profile'))
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
