"""initial schema

Revision ID: 8136b6d42047
Revises: 
Create Date: 2026-08-06 22:25:11.032481
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '8136b6d42047'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('cookie_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('has_valid_session', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_has_valid_session'), ['has_valid_session'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_username'), ['username'], unique=True)

    op.create_table('clip_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('source_platform', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('custom_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('caption_tags', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('original_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('source_metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clip_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clip_jobs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clip_jobs_source_platform'), ['source_platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_clip_jobs_status'), ['status'], unique=False)

    op.create_table('login_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_sessions_username'), ['username'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('irreversible', sa.Boolean(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('result_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_cancel_requested'), ['cancel_requested'], unique=False)
        batch_op.create_index('ix_tasks_claim', ['status', 'kind', 'run_at', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_tasks_lease', ['status', 'lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_run_at'), ['run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('video_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('cover_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['clip_jobs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clips_index'), ['index'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_clips_job_order', ['job_id', 'index'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_task_id'), ['task_id'], unique=False)

    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('source_kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(length=2200), nullable=False),
    sa.Column('options_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('result_text', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publications_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_clip_id'), ['clip_id'], unique=False)
        batch_op.create_index('ix_publications_clip_status', ['clip_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_task_id'))
        batch_op.drop_index(batch_op.f('ix_publications_status'))
        batch_op.drop_index(batch_op.f('ix_publications_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_publications_owner_id'))
        batch_op.drop_index('ix_publications_clip_status')
        batch_op.drop_index(batch_op.f('ix_publications_clip_id'))
        batch_op.drop_index(batch_op.f('ix_publications_account_id'))

    op.drop_table('publications')
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clips_task_id'))
        batch_op.drop_index(batch_op.f('ix_clips_status'))
        batch_op.drop_index('ix_clips_job_order')
        batch_op.drop_index(batch_op.f('ix_clips_job_id'))
        batch_op.drop_index(batch_op.f('ix_clips_index'))

    op.drop_table('clips')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_run_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_tasks_lease_expires_at'))
        batch_op.drop_index('ix_tasks_lease')
        batch_op.drop_index(batch_op.f('ix_tasks_kind'))
        batch_op.drop_index('ix_tasks_claim')
        batch_op.drop_index(batch_op.f('ix_tasks_cancel_requested'))

    op.drop_table('tasks')
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_sessions_username'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_status'))

    op.drop_table('login_sessions')
    with op.batch_alter_table('clip_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clip_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_clip_jobs_source_platform'))
        batch_op.drop_index(batch_op.f('ix_clip_jobs_owner_id'))

    op.drop_table('clip_jobs')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_username'))
        batch_op.drop_index(batch_op.f('ix_accounts_owner_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_has_valid_session'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
